export const wordMap: Record<string | number, string[]> = {
"01": ["Soda"],
  "07": ["Sock"],

  0: ["Sew", "Sea", "Sue"],

    1: ["Tea", "Tie", "Toe", "Tee"],
    2: ["Noah", "New", "Knee"],
    3: ["Ma", "May", "Mow"],
    4: ["Ray", "Rye", "Row"],
    5: ["Law", "Lay", "Lee"],
    6: ["Shoe", "Shy", "Show", "Jaw"],
    7: ["Key", "Cow", "Kay"],
    8: ["Fee", "Foe", "Few"],
    9: ["Pie", "Pea", "Pay"],

    10: ["Toes", "Dice", "Dose"],
    11: ["Tot", "Tight", "Tide"],
    12: ["Tin", "Tune", "Teen"],
    13: ["Tomb", "Team", "Tame"],
    14: ["Tire", "Tear", "Door"],
    15: ["Tail", "Doll", "Deal"],
    16: ["Dish", "Dash", "Ditch"],
    17: ["Tack", "Duck", "Deck", "Taco"],
    18: ["Dove", "Dive", "Duff"],
    19: ["Tub", "Tape", "Top"],

    20: ["Nose", "Nice", "Noose"],
    21: ["Net", "Knot", "Night"],
    22: ["Nun", "Nanny", "Onion"],
    23: ["Name", "Gnome", "Enemy"],
    24: ["Nero", "Narrow", "Honor"],
    25: ["Nail", "Anvil", "Neil"],
    26: ["Notch", "Niche", "Nacho"],
    27: ["Neck", "Nick", "Knock"],
    28: ["Knife", "Navy", "Naive"],
    29: ["Knob", "Nap", "Nub", "Noob"],

    30: ["Moss", "Moose", "Maze"],
    31: ["Mat", "Mate", "Meat"],
    32: ["Moon", "Mine", "Man"],
    33: ["Mummy", "Meme", "Mame"],
    34: ["Mare", "Mirror", "More"],
    35: ["Mule", "Mail", "Meal"],
    36: ["Match", "Mash", "Midge"],
    37: ["Mug", "Mike", "Mack"],
    38: ["Movie", "Muff", "Mafia"],
    39: ["Map", "Mob", "Mop"],

    40: ["Rose", "Rice", "Ruse"],
    41: ["Rat", "Road", "Root"],
    42: ["Rain", "Rune", "Run"],
    43: ["Ram", "Room", "Rim"],
    44: ["Roar", "Rare", "Rower"],
    45: ["Roll", "Rail", "Rill"],
    46: ["Rush", "Rash", "Ridge"],
    47: ["Rock", "Rack", "Rick"],
    48: ["Roof", "Reef", "Rave"],
    49: ["Rope", "Rib", "Ripe"],

    50: ["Lace", "Lass", "Loss"],
    51: ["Lot", "Lad", "Late"],
    52: ["Lion", "Lane", "Loan"],
    53: ["Lamb", "Loom", "Lime"],
    54: ["Lair", "Lore", "Lyre"],
    55: ["Lily", "Lull", "Lolly"],
    56: ["Leech", "Latch", "Lash"],
    57: ["Lock", "Lake", "Leak"],
    58: ["Leaf", "Loaf", "Love"],
    59: ["Lip", "Loop", "Leap"],

    60: ["Cheese", "Chase", "Chess"],
    61: ["Chat", "Sheet", "Shot"],
    62: ["Chain", "Shin", "Shone"],
    63: ["Jam", "Sham", "Chime"],
    64: ["Cherry", "Chair", "Share"],
    65: ["Shell", "Shale", "Jail"],
    66: ["Judge", "Shush", "Choosh"],
    67: ["Chalk", "Shake", "Shock"],
    68: ["Chef", "Shove", "Chief"],
    69: ["Ship", "Shape", "Shop"],

    70: ["Case", "Keys", "Kiss"],
    71: ["Cat", "Cut", "Coat"],
    72: ["Cane", "Coin", "Can"],
    73: ["Comb", "Came", "Game"],
    74: ["Car", "Core", "Care"],
    75: ["Coal", "Call", "Kill"],
    76: ["Cage", "Catch", "Cash"],
    77: ["Cake", "Cook", "Geek"],
    78: ["Cave", "Cuff", "Calf"],
    79: ["Cap", "Cab", "Cup"],

    80: ["Face", "Fuzz", "Vase"],
    81: ["Fat", "Foot", "Fit"],
    82: ["Fan", "Phone", "Fun"],
    83: ["Foam", "Fame", "Fume"],
    84: ["Fire", "Fair", "Fur"],
    85: ["Fall", "Foil", "Fail"],
    86: ["Fish", "Fetch", "Fudge"],
    87: ["Fig", "Fake", "Fog"],
    88: ["Fife", "Foe-Foe", "Fever"],
    89: ["Fib", "Fob", "Fob", "FBI"],

    90: ["Pus", "Paws", "Peace"],
    91: ["Pot", "Pad", "Pit"],
    92: ["Pan", "Pine", "Pen"],
    93: ["Palm", "Pom", "Poem"],
    94: ["Pear", "Pure", "Pour"],
    95: ["Pool", "Pill", "Pail"],
    96: ["Peach", "Patch", "Bush"],
    97: ["Pig", "Pack", "Poke"],
    98: ["Puff", "Pave", "Beef"],
    99: ["Pup", "Pipe", "Pop"],

    100: ["Daisies", "Toss", "Deuce"],
}